language: cpp

jdk:
- oraclejdk8

matrix:
  include:
    - os: linux
      addons:
        apt: 
          packages:
            - clang-3.8
            - gnuplot

    - os: linux
      env: PREFER_GCC=true
      addons:
        apt:
          packages:
            - g++-5
            - gnuplot

script:
- ./gradlew build --stacktrace

notifications:
  email: false