# Run tests with Visual Studio 2017
image: Visual Studio 2017

environment:
  matrix:
    - CI_COMPILER: CLANG
    - CI_COMPILER: GCC

# Install submodules
install:
  - git submodule update --init
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - set CC=clang-cl
  - set CXX=clang-cl
  - clang-cl -v

build_script:
  - gradlew.bat build --stacktrace --console=plain -PwithBench

# Cache gradle downloads
cache:
  - C:\Users\appveyor\.gradle
