resources:
  containers:
  - container: wpilib2019
    image: jaci/azure-native-linux:2018.11.14

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  variables:
    PlatformName: "win"
  steps:
  - template: azure-steps.yml
    parameters:
      env: { }

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
    PlatformName: "mac"
  steps:
  - template: azure-steps.yml
    parameters:
      env: { }

- job: LinuxGCC
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: wpilib2019
  variables:
    PlatformName: "linuxGCC"
  steps:
  - template: azure-steps.yml
    parameters:
      env: { "CI_COMPILER": "GCC" }

- job: LinuxClang
  pool: 
    vmImage: 'Ubuntu-16.04'
  container: wpilib2019
  variables:
    PlatformName: "linuxClang"
  steps:
  - template: azure-steps.yml
    parameters:
      env: { "CI_COMPILER": "CLANG" }
